### ISSUE TITLE
Failed axios request

### ISSUE THREAD

**Issue by JoshFink** [cyberofficial/TTVDropBot#11]
Hi, I just noticed this error this morning. It's happening on the Zaarrg fork as well as this one. I'm guessing it's a Twitch issue but wanted to at least log it. 

`Failed axios Request... Retrying in 60 seconds... Try: 1/3 Error: connect ETIMEDOUT 144.91.124.143:3004`

Though, honestly, not sure why it's connecting out to a German IP address. Weird. (or maybe not)

Thanks

**Comment by Donkeykong307** [comment]
It's the inbuilt update checker.

**Comment by MrHugelberg** [comment]
> It's the inbuilt update checker.

no way to disable it?

**Comment by cyberofficial** [comment]
Fixed with version 00.04 https://github.com/cyberofficial/TTVDropBot/releases/tag/0.04
