### ISSUE TITLE
Getting GQL RESPONSE ERROR! DropsPage_ClaimDropRewards on Linux Version

### ISSUE THREAD

**Issue by framilano** [cyberofficial/TTVDropBot#3]
After completing one drop, it tries to claim it (even if I set autoClaim as false) and then the infamouse DropsPage error shows up and completely lock any other drop from being unlocked. 

It keeps giving me error if I restart it and I don't claim on twitch inventory page the unlocked drops. Any idea on why?

Edit: I just checked and the Windows version works gine (doesn't claim anything of course but at least it doesn't give the error and keeps unlocking the drops)

**Comment by cyberofficial** [comment]
Hey sorry for late response !

Can you tell me what linux architecture and kernel? (ie Debian x64, hard-float ARMv7 with NEON and ARMv8 etc)

**Comment by cyberofficial** [comment]
I have tried to rename some things around for better global operating system support

Try this build: 
[TTVDropBot-linux-x64.7z.zip](https://github.com/cyberofficial/TTVDropBot/files/9896641/TTVDropBot-linux-x64.7z.zip)


(you'll need 7z to unzip the file)

if that doesn't work, I'll try some other things, I'm still working on a better method of claiming drops; twitch really hardened their drops page with a bunch of broken stuff (seems like genuine poor dev work on their part, tons of things are not labeled right and broken scripts etc 😅)

This file worked for me on Debian x64 Kernel 6

**Comment by delta-whiplash** [comment]
hello I got the issue on the latest version ghcr.io/cyberofficial/ttvdropbot/ttvdropbot-patched:latest
Can someone explain how to do
