### ISSUE TITLE
Is there a way to restart the bot on crash without any user input?

### ISSUE THREAD

**Issue by MrHugelberg** [cyberofficial/TTVDropBot#8]
title says all pretty much.
I am using the failsafe start bat and when it crashes(wich it does many many times in its current state unfortunately), it stays on drop selection until I choose something.
I don't really care what drops it claims, I just let it run for everything so it would be cool when it just chooses something random so it at least continues without any user input.

apologize in advance if this does not belong here. Not really a bug report I know.

**Comment by cyberofficial** [comment]
check out Important Info #10 post, I will be recreating the code and updating most of the issues.
Sorry for the delayed response.

**Comment by sffxzzp** [comment]
You mentioned a `failsafe.bat`, my understanding is the batch file restarts the bot when it crashes.

If it is, my solution is set "displayless" to true, and set "Prioritylist" to [] in config.json.
``` json
{
  "displayless": false,
  "Prioritylist": []
}
```

"displayless" will skip the selection part, and leave nothing in "Prioritylist" will make the bot to farm a random game.

**Comment by MrHugelberg** [comment]
> You mentioned a `failsafe.bat`, my understanding is the batch file restarts the bot when it crashes.
> 
> If it is, my solution is set "displayless" to true, and set "Prioritylist" to [] in config.json.
> 
> ```json
> {
>   "displayless": false,
>   "Prioritylist": []
> }
> ```
> 
> "displayless" will skip the selection part, and leave nothing in "Prioritylist" will make the bot to farm a random game.

oh my god, I kinda feel stupid now.. yea that was bascailly exactly what I was looking for! ty
